### ISSUE TITLE
Monster Hunter Rise Subreak Amiibo unable to be scanned successfully

### ISSUE THREAD

**Issue by kingblinx** [Gioman101/FlipperAmiibo#10]
When scanning the [Malzeno.nfc](https://github.com/Gioman101/FlipperAmiibo/blob/main/Monster%20Hunter/MH_%20Rise/Malzeno.nfc) , [Palamute Canyne Malzeno.nfc](https://github.com/Gioman101/FlipperAmiibo/blob/main/Monster%20Hunter/MH_%20Rise/Palamute%20Canyne%20Malzeno.nfc), and [Palico Felyne Malzeno.nfc](https://github.com/Gioman101/FlipperAmiibo/blob/main/Monster%20Hunter/MH_%20Rise/Palico%20Felyne%20Malzeno.nfc) Amiibo, I am getting a generic error "This is not an amiibo." with error code 2115-0176 in Monster Hunter Rise: Sunbreak. Older amiibo are working fine for other games. I even tested amiibo from monster hunter stories and they scanned fine in sunbreak, it is just the three new ones that are not scanning. 

<a href="https://imgur.com/gQggPgE"><img src="https://i.imgur.com/gQggPgE.jpg" title="source: imgur.com" /></a>

**Comment by kingblinx** [comment]
Forgot to mention that a .SHD file is created on the SD card with the same name as the Amiibo after scanning. For example, when scanning the Malzeno.nfc, a file called Malzeno.shd is created in the same directory. I have attached the file for reference.
[Malzeno.zip](https://github.com/Gioman101/FlipperAmiibo/files/9033815/Malzeno.zip)

It appears the only differences between the NFC and SHD file is that the Mifare Classic option is added on the line "Nfc device type can be", the "Counter 2" option changes from 0 to 2, and a new line is added to the bottom that says "Failed authentication attempts: 1" on the SHD file.

**Comment by RogueMaster** [comment]
This is possible due to an issue with the converter PY script and PWD/PACK on the last pages. I opened an issue there...

**Comment by Woopah** [comment]
same issue, with DIABLO

**Comment by Lanjelin** [comment]
This issue seems to be mostly linked wrong size of the .bin-files used as source, as I assume all these files are generated using the known PY script.

The size of the .bin-files are supposed to be 540bytes it seems, the ones tossing "This is not an amiibo"-error are 532 or 572bytes.

Editing .bin-files, appending `0000 0000 0000 0000` at the end, I've successfully managed to fix all the the 532byte files (making them 540bytes).

For the .nfc-files, this means you need to change `Pages total` to `135`, and appending the following two lines at the end
```
Page 133: 00 00 00 00
Page 134: 00 00 00 00
```
As for the .nfc with 572bytes .bin source, I've managed to get Qbby.nfc working by removing Pages exceeding 134, and setting `Pages total` to `135`.

Oh, and when you're done modifying the files on the SD-card, delete the .shd-files, as it seems to be some sort of runtime-cache the Flipper uses.

I've made my own collection with some other naming scheme, as I'm planning to make folders for what games the Amiibos are used, as well as folders for series. Currently editing all the .bins, once I'm done testing the changes, I'll make a PR with the fixes.
