### ISSUE TITLE
Pikmin.nfc Does Not Work on Switch

### ISSUE THREAD

**Issue by PaulWGeorge** [Gioman101/FlipperAmiibo#34]
Tried to emulate it and Switch did not recognize it as an Amiibo.

**Comment by kidpresident0** [comment]
Same thing happened to me for the Zelda ones. I tried all of them on Tears of The Kingdom and couldn't get any of them to emulate. Saw a post on reddit for adjusting the position of the flipper over the Switch controller in a certain way and that did not work either.

**Comment by tim3dsource** [comment]
See if this TOTK video helps https://youtu.be/uTctCZY48Jg (sorry for the quality)

**Comment by j123456780** [comment]
Check this, so you can see where the nfc is, by the way, if it sounds like there is an error, it does not mean that the amiibo has problems, but that the position in which you are placing it is wrong and the tag cannot be read correctly .

![image](https://github.com/Gioman101/FlipperAmiibo/assets/109506865/d76fa212-2b45-4609-aabb-04be0b47acb7)


By the way, I have emulated with flipper and read the file from my iphone (amiiboss) and everything works fine.

![image](https://github.com/Gioman101/FlipperAmiibo/assets/109506865/010c24bc-e4cd-483c-9f0a-0f4792ed7372)

**Comment by kidpresident0** [comment]
Thank you for all your help. I am actually such a moron I should have come back on here and comment. I was only looking at the pause menu where it said amiibo enabled but I was not going into my little ability wheel and choosing amiibo. LOL. It had been a while since breath of the Wild.Soooo stupid.😄 works great now.
