### ISSUE TITLE
No amiibo nfc's are working with my switch

### ISSUE THREAD

**Issue by wifininja** [Gioman101/FlipperAmiibo#48]
Readers: Pro Controller / Joycon
OLED Switch

flipper zero fw 94.1

Emulating any amiibo tag results in:
BOTW/Totk - Nothing happening
Mario Kart 8 - Either "Unable to read data. This item may not be an amiibo" or "Unable to read data from the amiibo" * Depending on what position I have the f0 in
System > amiibo > All options - "This is not an amiibo" * No matter what position I have it in to read the nfc

**Comment by bl13pbl03p** [comment]
Same issue here after updating to Release 0.94.1. Switch did not recognize Amiibo cards from ACNH. Initially, it was also not possible to emulate actual Amiibo cards. But through: `NFC > Extra Actions > Unlock NTAG/Ultralight > Auth as Ameebo` and then scanning a original Amiibo card sortof fixed the issue. Maybe it will be fixed in the next Flipper release!

**Comment by h0b0byter99** [comment]
After updating to Release 0.94.1 none of these amiibos work. I did scan then with the Tagmiibo iPhone app and they were able to be read by the Tagmiibo.

**Comment by u1735067** [comment]
The forked `.bin` -> `.nfc` converter at https://github.com/Lanjelin/AmiiboFlipperConverter/pull/1/files might fix that, but I have not tested (related: https://github.com/Lucaslhm/AmiiboFlipperConverter/issues/5). Otherwise writing a script to fix the existing `.nfc` should be easy too.
